rules:
  no-unused-vars:
    - error
    - vars: local
  comma-spacing: error
  no-const-assign: error
  # array-bracket-spacing: error
  space-in-parens:
    - error
    - never
  # camelcase: error
  indent:
    - error
    - 2
  dot-notation:
    - error
    - allowPattern: ^[a-z]+(_[a-z]+)+$
  comma-dangle:
    - error
    - always
env:
  es6: true
  browser: true
  jquery: true
extends:
  - 'eslint:recommended'
